# Generated by Django 4.2.7 on 2023-11-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=50, verbose_name='Nome do jogador')),
                ('key', models.CharField(max_length=60, verbose_name='Chave da mira')),
            ],
        ),
    ]
