# Generated by Django 4.2.7 on 2023-11-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_key',
            name='key',
            field=models.CharField(max_length=100, verbose_name='Chave da mira'),
        ),
    ]
